branch-defaults:
  master:
    environment: arthology-api
    group_suffix: null
global:
  application_name: arthology-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: arthology
  repository: null
  sc: git
  workspace_type: Application