# Generated by Django 3.2.5 on 2021-08-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file',
            new_name='filehash',
        ),
        migrations.AddField(
            model_name='product',
            name='fiat',
            field=models.IntegerField(choices=[(0, 'Ethereum'), (1, 'U.S. Dollar')], default=0, verbose_name='Fiat'),
        ),
    ]
