# Generated by Django 3.2.5 on 2021-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20210809_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='products',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='collection',
        ),
        migrations.AddField(
            model_name='gallery',
            name='products',
            field=models.ManyToManyField(blank=True, to='art.product'),
        ),
    ]
