# Generated by Django 3.2.5 on 2021-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_product_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
