# Generated by Django 3.2.5 on 2021-08-10 07:02

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_product_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='imgbabner',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.gallery_directory_path, verbose_name='Imagem Banner'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='imglogo',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.gallery_directory_path, verbose_name='Imagem Logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fileimage',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.artist_directory_path),
        ),
    ]
