# Generated by Django 3.2.5 on 2021-08-11 03:24

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_auto_20210810_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fileimage',
            field=models.FileField(blank=True, null=True, upload_to=art.models.artist_directory_path),
        ),
    ]
