# Generated by Django 3.2.5 on 2021-08-12 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0010_product_royalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='curator',
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='art.gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='filehash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cid'),
        ),
    ]
