# Generated by Django 3.2.5 on 2021-08-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_auto_20210812_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='art.gallery'),
        ),
    ]
