# Generated by Django 3.2.5 on 2021-08-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_auto_20210813_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filemeta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='meta cid'),
        ),
    ]
