# Generated by Django 3.2.5 on 2021-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0016_product_filemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mintingid',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Minting Id'),
        ),
    ]
