# Generated by Django 3.2.5 on 2021-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0019_auto_20210825_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'Digital'), (1, 'Physical')], default=0, verbose_name='Typw'),
        ),
    ]
