# Generated by Django 3.2.5 on 2021-08-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0021_auto_20210829_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
