# Generated by Django 3.2.5 on 2021-09-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0022_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fiat',
            field=models.IntegerField(choices=[(0, 'Ethereum'), (1, 'U.S. Dollar'), (2, 'Solana')], default=0, verbose_name='Fiat'),
        ),
    ]
