# Generated by Django 3.2.5 on 2021-10-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0024_auto_20211003_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualgallery',
            old_name='fileimage',
            new_name='file',
        ),
    ]
