# Generated by Django 3.2.5 on 2021-10-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0026_gallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='royalty',
            field=models.IntegerField(default=0),
        ),
    ]
