# Generated by Django 3.2.5 on 2021-08-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210823_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='circle_chainETH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
