# Generated by Django 3.2.5 on 2021-08-30 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_circle_chaineth'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardid', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.IntegerField(choices=[(0, 'Visa'), (1, 'Mastercard')], default=0, verbose_name='Card Flag')),
                ('last', models.CharField(blank=True, max_length=32, null=True)),
                ('cvv', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
